### ISSUE TITLE
question: how do i add sounds with datapacks?

### ISSUE THREAD

**Issue by memphismc** [ItsSyfe/auditory-continued#1]
a lot of modded blocks in my world are missing their auditory sounds and just have the regular stock minecraft sounds, id like to change that

**Comment by memphismc** [comment]
nevermind, found the template datapack

you can delete this sorry

**Comment by ItsSyfe** [comment]
just for future reference as this is currently a direct port, all of [the original developer guide](https://github.com/Sydokiddo/auditory/wiki/Developer-Guide) still applies

**Comment by memphismc** [comment]
> just for future reference as this is currently a direct port, all of [the original developer guide](https://github.com/Sydokiddo/auditory/wiki/Developer-Guide) still applies

i still have a problem with it, you see the stone ore sounds and metal sounds work ok

but the leaf sounds and plant do not, in fact it removes auditory's sounds and somehow replaces them with the vanilla ones despite the leaf block registries being in there
