### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by VeiTheOne** [ItsSyfe/auditory-continued#2]
I have a question, I thought the mod was Client side only. But whenever I play multiplayer, the sounds do not work, but they work just fine on single player. Something wrong?

**Comment by HacksoreDE** [comment]
I have the same problem and was wondering about that too.

**Comment by m0oncatcher** [comment]
Can confirm

**Comment by r3xsean** [comment]
still have the same problem, looking for a fix!

**Comment by JENOVAAbsolute** [comment]
> still have the same problem, looking for a fix!

The mod being labeled as client side only was probably a mistake. This mod is a port of the original Auditory, which was required on both the client and server. It's safe to assume there is no fix, because it's intentional. Install this mod on the server and see if it works.

**Comment by ItsSyfe** [comment]
closing as stale, i've marked it as client and server on both modrinth and curse now
