### ISSUE TITLE
1.21.1 support

### ISSUE THREAD

**Issue by SAJewers** [ItsSyfe/auditory-continued#8]
attempting to run on 1.21.1 gives this error

> Incompatible mods found!
> net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
> A potential solution has been determined, this may resolve your problem:
> 	 - Replace mod 'Auditory' (auditory) 0.0.7-1.21 with any version that is compatible with:
> 		 - minecraft 1.21.1
> More details:
> 	 - Mod 'Auditory' (auditory) 0.0.7-1.21 requires version 1.21 of 'Minecraft' (minecraft), but only the wrong version is present: 1.21.1!
> 	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51)
> 	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:196)
> 	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146)
> 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
> 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
> 	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100)
> 	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
> 	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)
>

**Comment by ItsSyfe** [comment]
closed by ce6f33d
